spring:
  application:
    name: Console-Server
  datasource:
    admin:
      url: "jdbc:mysql://localhost:3306/%s?useUnicode=true&characterEncoding=UTF8&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false"
      username: "root"
      password: "root"
    spider:
      url: "jdbc:mysql://localhost:3306/sun?useUnicode=true&characterEncoding=UTF8&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false"
      username: "root"
      password: "root"
    image:
      url: "jdbc:mysql://localhost:3306/sun?useUnicode=true&characterEncoding=UTF8&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false"
      username: "root"
      password: "root"

server:
  port: 9729
