server.port: 9727

spring:
  application:
    name: QM-Server
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:localhost:3306}/sun?useUnicode=true&characterEncoding=UTF8&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER_OF_QM:root}
    password: ${MYSQL_PASSWORD_OF_QM:root}

footprint.max: ${FOOTPRINT_MAX:100}
retrieve.password.key: ${RETRIEVE_PASSWORD_KEY:abcd}
gmail.username: ${GMAIL_USERNAME:xfanggirl2@gmail.com}
gmail.password: ${GMAIL_PASSWORD:cjunbmlztfuribvh}
server.http.domain: ${GMAIL_PASSWORD:http://localhost:1379/#/user/changePwd}
image.store.dir: ${IMAGE_STORE_DIR:/opt/static/image/qm}
