spring:
  application:
    name: Admin-Server
  datasource:
    admin:
      url: "jdbc:mysql://localhost:3306/%s?useUnicode=true&characterEncoding=UTF8&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false"
      username: "root"
      password: "root"

server:
  port: 9729
