server.port: 9729

spring:
  application:
    name: Rest-Server
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:49.232.14.106:3306}/sun?useUnicode=true&characterEncoding=UTF8&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false
    username: ${MYSQL_USER_OF_SUN:lins_sun}
    password: ${MYSQL_PASSWORD_OF_SUN:GahV.iJRr]su86Gfpxsf}
    admin:
      url: jdbc:mysql://${MYSQL_SERVER:49.232.14.106:3306}/%s?useUnicode=true&characterEncoding=UTF8&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false
      username: root
      password: ${MYSQL_ROOT_PASSWORD:GbrM_qFX.w9cYXFLtKj9}

category.cache.expire: ${CATEGORY_CACHE_EXPIRE:10}
